name: 

permissions: read-all

concurrency:
  group: ci-${{ github.ref }}

on:
  pull_request:
    branches: [main]

env:
    WAST_TARGET: wasm32-wasi

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4


      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install wasm target
        run: |
          rustup target add ${{ env.WAST_TARGET }}


      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        timeout-minutes: 10


      - name: Build
        timeout-minutes: 40
        run: make build
  

  # To satisfy the merge queue check       
  done:
    name: Done
    needs:
      - build
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Dump needs context
      env:
        CONTEXT: ${{ toJson(needs) }}
      run: |
        echo -e "\033[33;1;4mDump context\033[0m"
        echo -e "$CONTEXT\n"
    - name: Report failure on cancellation
      if: ${{ contains(needs.*.result, 'cancelled') || cancelled() }}
      run: exit 1
    - name: Failing test and build
      if: ${{ contains(needs.*.result, 'failure') }}
      run: exit 1
    - name: Successful test and build
      if: ${{ !(contains(needs.*.result, 'failure')) }}
      run: exit 0
